modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="about:blank"
#displayURL="about:blank"
logoFile="8bit_mod_logo.png"

[[mods]]
modId="8bit"
version="${file.jarVersion}"
displayName="8-bit Mod"
#updateJSONURL="about:blank"


credits="Textures & Recipes by AwesomeNinja886, Manifest and file structure based upon the Super Tools Mod by TheLuigiplayer & KiritoGames20, other code based upon other mods (WIP)"
authors="AwesomeNinja886"
description='''
Test mod based upon the amazing Diary of an 8-bit Warrior series and to a lesser extent the Tales of an 8-bit Kitten series by Cube Kid'''


[[dependencies.8bit]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.8bit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2, 1.14.3]"
    ordering="NONE"
    side="BOTH"